# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-08 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blurb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
