# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-08 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170108_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blurb',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
