# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20161215_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpagesettings',
            name='faq',
        ),
        migrations.AddField(
            model_name='faqpagesettings',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
