# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20161215_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpagesettings',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
