# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20161215_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=100)),
                ('main_subtitle', models.CharField(max_length=100)),
                ('leaving_soon_heading', models.CharField(max_length=100)),
                ('services_heading_one', models.CharField(max_length=100)),
                ('services_blurb_one', models.CharField(max_length=150)),
                ('services_heading_two', models.CharField(max_length=100)),
                ('services_blurb_two', models.CharField(max_length=150)),
                ('services_heading_three', models.CharField(max_length=100)),
                ('services_blurb_three', models.CharField(max_length=150)),
                ('video', models.URLField()),
                ('news_heading', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
