# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_homepagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_blurb_one',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_blurb_three',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_blurb_two',
            field=models.TextField(max_length=150),
        ),
    ]
