# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20161219_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='services_image_one',
            field=models.ImageField(blank=True, upload_to=b'images/icons'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='services_image_three',
            field=models.ImageField(blank=True, upload_to=b'images/icons'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='services_image_two',
            field=models.ImageField(blank=True, upload_to=b'images/icons'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='leaving_soon_heading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='main_heading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='main_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_blurb_one',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_blurb_three',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_blurb_two',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_heading_one',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_heading_three',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_heading_two',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
