# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-20 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_auto_20161219_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='main_image',
        ),
    ]
