# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-20 01:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('site_settings', '0008_remove_homepagesettings_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='main_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumbotron_header_image', to='filer.Image'),
        ),
    ]
