# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-20 02:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('site_settings', '0010_auto_20161220_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='services_image_one',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_image_one', to='filer.Image'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='services_image_three',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_image_three', to='filer.Image'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='services_image_two',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_image_two', to='filer.Image'),
        ),
    ]
