# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
