# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20161215_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
