# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20161215_2128'),
        ('default', '0004_auto_20161215_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='faq_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_blocks', to='site_settings.FAQPageSettings'),
        ),
    ]
