# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_faqitem_faq_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
