# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20161215_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Form Message',
            },
        ),
    ]
