# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2017, 1, 6, 1, 41, 58, 285869, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2017, 1, 6, 1, 42, 5, 493644, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
